source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'WXScrollerSelector_Example' do
#  pod 'WXScrollerSelector', :path => '../'
  pod 'WXScrollerSelector', '0.1.3'
  
end
